

/* W5500 SPI-ETH Pins */
#define ETH_SPI_PHY_RST_GPIO (GPIO_NUM_4)
#define ETH_SPI_INT_GPIO     (GPIO_NUM_5)
#define ETH_SPI_MOSI_GPIO    (GPIO_NUM_6)
#define ETH_SPI_MISO_GPIO    (GPIO_NUM_7)
#define ETH_SPI_SCLK_GPIO    (GPIO_NUM_15)
#define ETH_SPI_CS_GPIO      (GPIO_NUM_16)
